### ISSUE TITLE
Ordinary reaction wheel control unavailable on small probe core craft

### ISSUE THREAD

**Issue by evanrinehart** [gotmachine/MandatoryRCS#10]
As I understood it reaction wheel control should be allowed on small satellites with probe cores. With a Probodobodyne OKTO core, which has reaction wheels, a oscar fuel tank, and ant engine only, the stabilization feature does work but arbitrary rotation using reaction wheels does not.

**Comment by gotmachine** [comment]
Should be fixed in 1.6
