### ISSUE TITLE
Reaction wheel control returns to normal sometimes at the end of mission

### ISSUE THREAD

**Issue by evanrinehart** [gotmachine/MandatoryRCS#11]
About 50% of the time in a mission such as the following
  - launch a pod to a space station
  - dock with station
  - undock from station and do de-orbit burn
  - decouple pod and reenter

reaction wheel control for the pod behaves like in stock KSP after the final decoupling.

The other 50% of the time, reaction wheel for the pod completely does not work by that point, not even stabilization, see https://github.com/gotmachine/MandatoryRCS/issues/7

**Comment by gotmachine** [comment]
Should be fixed in 1.6
