### ISSUE TITLE
On 'realistic' difficulty manned pods can effectively turn using SAS

### ISSUE THREAD

**Issue by evanrinehart** [gotmachine/MandatoryRCS#8]
The SAS selector to point in a particular direction basically works, albeit in a labored manner, for manned craft even ones that are not particularly light weight.

This definitely happens earlier in missions. I sometimes notice it going away later in missions, but it may be due to the docking-disables-your-reaction-wheels issue. https://github.com/gotmachine/MandatoryRCS/issues/7

**Comment by gotmachine** [comment]
Should be fixed in 1.6
